#CloudBuild file


steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['echo', 'Building...']
  options:
    logsBucket: 'gs://your-custom-logs-bucket'
  id: BUILD

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['echo', 'Testing...']
  options:
    logsBucket: 'gs://your-custom-logs-bucket'
  id: TEST

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - $_FUNCTION_NAME
  - --region=$_FUNCTION_REGION
  - --source=.
  - --trigger-http
  - --runtime=$_FUNCTION_RUNTIME
  - --project=$_FUNCTION_PROJECT
  - --entry-point=$_ENTRY_POINT
  options:
    logsBucket: 'gs://your-custom-logs-bucket'
  id: DEPLOY

substitutions:
    _FUNCTION_PROJECT : staging
    _FUNCTION_NAME    : my-nodejs-app
    _FUNCTION_REGION  : europe-west1
    _FUNCTION_RUNTIME : nodejs22
    _ENTRY_POINT      : helloHttp
